# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\nstevenson\AppData\Roaming\Luxology\Scripts\europa\uiMain.ui'
#
# Created: Tue Nov 03 16:51:48 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_EuropaExporter(object):
    def setupUi(self, EuropaExporter):
        EuropaExporter.setObjectName("EuropaExporter")
        EuropaExporter.resize(926, 488)
        EuropaExporter.setMinimumSize(QtCore.QSize(926, 0))
        self.centralwidget = QtGui.QWidget(EuropaExporter)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout = QtGui.QHBoxLayout(self.tab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_6.setSpacing(3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.scrollArea = QtGui.QScrollArea(self.groupBox)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 650, 271))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setContentsMargins(9, -1, -1, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.exportEntriesTitles_BoxLayout = QtGui.QHBoxLayout()
        self.exportEntriesTitles_BoxLayout.setObjectName("exportEntriesTitles_BoxLayout")
        self.label_10 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_10.setMaximumSize(QtCore.QSize(35, 16777215))
        self.label_10.setObjectName("label_10")
        self.exportEntriesTitles_BoxLayout.addWidget(self.label_10)
        self.label_5 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_5.setObjectName("label_5")
        self.exportEntriesTitles_BoxLayout.addWidget(self.label_5)
        self.label_6 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_6.setMaximumSize(QtCore.QSize(190, 16777215))
        self.label_6.setObjectName("label_6")
        self.exportEntriesTitles_BoxLayout.addWidget(self.label_6)
        self.label_7 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_7.setObjectName("label_7")
        self.exportEntriesTitles_BoxLayout.addWidget(self.label_7)
        self.verticalLayout_4.addLayout(self.exportEntriesTitles_BoxLayout)
        self.modelExportList_BoxLayout = QtGui.QVBoxLayout()
        self.modelExportList_BoxLayout.setSpacing(0)
        self.modelExportList_BoxLayout.setContentsMargins(3, 3, 3, 3)
        self.modelExportList_BoxLayout.setObjectName("modelExportList_BoxLayout")
        self.verticalLayout_4.addLayout(self.modelExportList_BoxLayout)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_6.addWidget(self.scrollArea)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_7.addWidget(self.label_4)
        self.addEntry_PushButton = QtGui.QPushButton(self.groupBox)
        self.addEntry_PushButton.setMinimumSize(QtCore.QSize(35, 30))
        self.addEntry_PushButton.setMaximumSize(QtCore.QSize(35, 30))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.addEntry_PushButton.setFont(font)
        self.addEntry_PushButton.setObjectName("addEntry_PushButton")
        self.horizontalLayout_7.addWidget(self.addEntry_PushButton)
        self.deleteEntry_PushButton = QtGui.QPushButton(self.groupBox)
        self.deleteEntry_PushButton.setMinimumSize(QtCore.QSize(35, 30))
        self.deleteEntry_PushButton.setMaximumSize(QtCore.QSize(35, 30))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.deleteEntry_PushButton.setFont(font)
        self.deleteEntry_PushButton.setObjectName("deleteEntry_PushButton")
        self.horizontalLayout_7.addWidget(self.deleteEntry_PushButton)
        spacerItem2 = QtGui.QSpacerItem(80, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.refresh_pushButton = QtGui.QPushButton(self.groupBox)
        self.refresh_pushButton.setMinimumSize(QtCore.QSize(35, 30))
        self.refresh_pushButton.setMaximumSize(QtCore.QSize(35, 30))
        font = QtGui.QFont()
        font.setFamily("Wingdings 3")
        self.refresh_pushButton.setFont(font)
        self.refresh_pushButton.setObjectName("refresh_pushButton")
        self.horizontalLayout_7.addWidget(self.refresh_pushButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.groupBox_3 = QtGui.QGroupBox(self.tab)
        self.groupBox_3.setMinimumSize(QtCore.QSize(160, 0))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_2.setSpacing(4)
        self.horizontalLayout_2.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_8 = QtGui.QLabel(self.groupBox_3)
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.exporter_ComboBox = QtGui.QComboBox(self.groupBox_3)
        self.exporter_ComboBox.setMinimumSize(QtCore.QSize(100, 0))
        self.exporter_ComboBox.setObjectName("exporter_ComboBox")
        self.exporter_ComboBox.addItem("")
        self.exporter_ComboBox.addItem("")
        self.exporter_ComboBox.addItem("")
        self.exporter_ComboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.exporter_ComboBox)
        self.horizontalLayout_4.addWidget(self.groupBox_3)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.exportSelected_PushButton = QtGui.QPushButton(self.tab)
        self.exportSelected_PushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.exportSelected_PushButton.setObjectName("exportSelected_PushButton")
        self.horizontalLayout_4.addWidget(self.exportSelected_PushButton)
        self.exportAll_PushButton = QtGui.QPushButton(self.tab)
        self.exportAll_PushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.exportAll_PushButton.setObjectName("exportAll_PushButton")
        self.horizontalLayout_4.addWidget(self.exportAll_PushButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.groupBox_4 = QtGui.QGroupBox(self.tab)
        self.groupBox_4.setMaximumSize(QtCore.QSize(200, 16777215))
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setSpacing(9)
        self.verticalLayout_5.setContentsMargins(3, 2, 3, 3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_11 = QtGui.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setWordWrap(True)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_5.addWidget(self.label_11)
        self.modelMeshes_groupBox = QtGui.QGroupBox(self.groupBox_4)
        self.modelMeshes_groupBox.setObjectName("modelMeshes_groupBox")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.modelMeshes_groupBox)
        self.verticalLayout_7.setSpacing(2)
        self.verticalLayout_7.setContentsMargins(2, 9, 2, 2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.modelMeshExports_ListView = QtGui.QListView(self.modelMeshes_groupBox)
        self.modelMeshExports_ListView.setObjectName("modelMeshExports_ListView")
        self.verticalLayout_7.addWidget(self.modelMeshExports_ListView)
        self.verticalLayout_5.addWidget(self.modelMeshes_groupBox)
        self.modelJoints_groupBox = QtGui.QGroupBox(self.groupBox_4)
        self.modelJoints_groupBox.setObjectName("modelJoints_groupBox")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.modelJoints_groupBox)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setContentsMargins(2, 9, 2, 2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.modelJointExports_ListView = QtGui.QListView(self.modelJoints_groupBox)
        self.modelJointExports_ListView.setObjectName("modelJointExports_ListView")
        self.verticalLayout_2.addWidget(self.modelJointExports_ListView)
        self.verticalLayout_5.addWidget(self.modelJoints_groupBox)
        self.modelMaterials_groupBox = QtGui.QGroupBox(self.groupBox_4)
        self.modelMaterials_groupBox.setObjectName("modelMaterials_groupBox")
        self.verticalLayout = QtGui.QVBoxLayout(self.modelMaterials_groupBox)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setContentsMargins(2, 9, 2, 2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.modelMaterialExports_ListView = QtGui.QListView(self.modelMaterials_groupBox)
        self.modelMaterialExports_ListView.setObjectName("modelMaterialExports_ListView")
        self.verticalLayout.addWidget(self.modelMaterialExports_ListView)
        self.verticalLayout_5.addWidget(self.modelMaterials_groupBox)
        self.verticalLayout_10.addLayout(self.verticalLayout_5)
        self.verticalLayout_9.addLayout(self.verticalLayout_10)
        self.horizontalLayout.addWidget(self.groupBox_4)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout_6.addWidget(self.tabWidget)
        EuropaExporter.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(EuropaExporter)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 926, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        EuropaExporter.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(EuropaExporter)
        self.statusbar.setObjectName("statusbar")
        EuropaExporter.setStatusBar(self.statusbar)
        self.importMD5Model_Action = QtGui.QAction(EuropaExporter)
        self.importMD5Model_Action.setObjectName("importMD5Model_Action")
        self.importMD5Animation_Action = QtGui.QAction(EuropaExporter)
        self.importMD5Animation_Action.setObjectName("importMD5Animation_Action")
        self.menuFile.addAction(self.importMD5Model_Action)
        self.menuFile.addAction(self.importMD5Animation_Action)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(EuropaExporter)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(EuropaExporter)

    def retranslateUi(self, EuropaExporter):
        EuropaExporter.setWindowTitle(QtGui.QApplication.translate("EuropaExporter", "Europa Exporter", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("EuropaExporter", "Export Entries", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("EuropaExporter", "Group", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("EuropaExporter", "Select", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("EuropaExporter", "Model Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("EuropaExporter", "Export Path", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("EuropaExporter", "Export Entries", None, QtGui.QApplication.UnicodeUTF8))
        self.addEntry_PushButton.setText(QtGui.QApplication.translate("EuropaExporter", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteEntry_PushButton.setText(QtGui.QApplication.translate("EuropaExporter", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.refresh_pushButton.setText(QtGui.QApplication.translate("EuropaExporter", "P", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("EuropaExporter", "Exporter", None, QtGui.QApplication.UnicodeUTF8))
        self.exporter_ComboBox.setItemText(0, QtGui.QApplication.translate("EuropaExporter", "MD5", None, QtGui.QApplication.UnicodeUTF8))
        self.exporter_ComboBox.setItemText(1, QtGui.QApplication.translate("EuropaExporter", "MD6", None, QtGui.QApplication.UnicodeUTF8))
        self.exporter_ComboBox.setItemText(2, QtGui.QApplication.translate("EuropaExporter", "Unreal", None, QtGui.QApplication.UnicodeUTF8))
        self.exporter_ComboBox.setItemText(3, QtGui.QApplication.translate("EuropaExporter", "Unity", None, QtGui.QApplication.UnicodeUTF8))
        self.exportSelected_PushButton.setText(QtGui.QApplication.translate("EuropaExporter", "Export Selected", None, QtGui.QApplication.UnicodeUTF8))
        self.exportAll_PushButton.setText(QtGui.QApplication.translate("EuropaExporter", "Export All", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("EuropaExporter", "Exports", None, QtGui.QApplication.UnicodeUTF8))
        self.modelMeshes_groupBox.setTitle(QtGui.QApplication.translate("EuropaExporter", "Meshes", None, QtGui.QApplication.UnicodeUTF8))
        self.modelJoints_groupBox.setTitle(QtGui.QApplication.translate("EuropaExporter", "Joints", None, QtGui.QApplication.UnicodeUTF8))
        self.modelMaterials_groupBox.setTitle(QtGui.QApplication.translate("EuropaExporter", "Materials", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("EuropaExporter", "Model Export", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("EuropaExporter", "Animation Export", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("EuropaExporter", "Import", None, QtGui.QApplication.UnicodeUTF8))
        self.importMD5Model_Action.setText(QtGui.QApplication.translate("EuropaExporter", "MD5 Model", None, QtGui.QApplication.UnicodeUTF8))
        self.importMD5Animation_Action.setText(QtGui.QApplication.translate("EuropaExporter", "MD5 Anim", None, QtGui.QApplication.UnicodeUTF8))

